/**
 * This file includes all the declaration of NCS windows.
 *
 * Please don't edit me.
 * 
 * This file is autogenerated by miniStudio.
 *
 * NOTE: ANY WORD WRITTEN BY USER WOULD BE DELETE BY MINISTUDIO !
 *
 */

#ifndef NCS_MAINWNDS_H
#define NCS_MAINWNDS_H

#ifdef __cpluspus
extern "C" {
#endif

/**
 * If you want to export these ncs main window function
 * to other libraries, please predefined marco NCS_WND_EXPORT, 
 */
#ifndef NCS_WND_EXPORT
#define NCS_WND_EXPORT
#endif

/**
 * If you want to pass a speical structure pointer by 'user_data'
 * to a main window, please modify the ncs-window-types.h.
 *
 */
#include "ncs-window-types.h"



/** define the function for ID_FONTSELECT */
extern NCS_WND_EXPORT 
mMainWnd * ntCreateFontselectEx(HPACKAGE package, HWND hParent, HICON h_icon, HMENU h_menu, DWORD user_dat);
#define ntCreateFontselect(package, hParent, user_data) \
	ntCreateFontselectEx(package, hParent, (HICON)0, (HMENU)0, (DWORD)(user_data))


/** define the start window */
#define ntStartWindowEx  ntCreateFontselectEx
#define ntStartWindow(package, hParent, user_data) \
	ntStartWindowEx(package, hParent, (HICON)0, (HMENU)0, (DWORD)(user_data))


#ifdef __cplusplus
}
#endif

#endif /* end of window list */

